### ISSUE TITLE
Blue screen after loading the driver

### ISSUE THREAD

**Issue by Clownsw** [sooqua/VanderLeague#2]
Blue screen after loading the driver

Windows 10 1909

**Comment by sooqua** [comment]
Error message?
Do you have an Intel processor with VT-x support enabled?

**Comment by Clownsw** [comment]
> 错误信息？
> 您是否具有启用了VT-x支持的Intel处理器？

I enabled AMD processor that supports VT-x

**Comment by sooqua** [comment]
AMD processors do not support VT-x, it's AMD-V and hvpp does not support it, sorry.
